np.vsplit

In [2]:
import numpy as np
m = 11
n = 10
X = np.random.uniform(low=0.0, high=1.0, size=(m,n)).astype(np.float64)
b = 2  # number of buckets
buckets = np.vsplit(X, [(m//b)*i for i in range(1,b)])


In [3]:
a = np.vsplit(X,2)
print(a)

ValueError: array split does not result in an equal division

In [5]:
a= np.array_split(X,2,axis=0)
print(a)

[array([[0.45354847, 0.28713839, 0.71430957, 0.46750708, 0.26407707,
        0.63970922, 0.66648436, 0.40121148, 0.14191529, 0.85363087],
       [0.21510478, 0.37655338, 0.59462436, 0.12733911, 0.51375911,
        0.97246873, 0.57305652, 0.08323697, 0.59648444, 0.13197574],
       [0.92283569, 0.55446521, 0.54906815, 0.41111929, 0.36422172,
        0.9300186 , 0.10980606, 0.83120215, 0.88066093, 0.08374764],
       [0.80694831, 0.58957212, 0.53265952, 0.3814776 , 0.49768278,
        0.65053806, 0.39031802, 0.95493129, 0.42661691, 0.48524473],
       [0.17269267, 0.09378524, 0.60840253, 0.62022545, 0.91291257,
        0.19817303, 0.63915604, 0.02539172, 0.88071395, 0.02427266],
       [0.96562792, 0.1231426 , 0.50994083, 0.80789172, 0.04754818,
        0.92148186, 0.77151105, 0.91195167, 0.81719583, 0.52364173]]), array([[0.92367975, 0.47353747, 0.21283851, 0.72027952, 0.37278303,
        0.32607697, 0.1365673 , 0.07213047, 0.9652038 , 0.34646553],
       [0.33264179, 0.08693317, 0.0449

In [14]:
b = np.sum(np.fromiter(a))
print(b)

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [4]:
m = 11
n = 10
X = np.random.uniform(low=0.0, high=1.0, size=(m,n)).astype(np.float64)
b=2  #no. of buckets
buckets = np.vsplit(X, [(m//b)*i for i in range(1,b)])
# Compute the mean within each bucket
b_means = [np.mean(x, axis=0) for x in buckets]
# Compute the median-of-means
median = np.median(np.array(b_means), axis=0)
print(median) #(n,) shaped array

[0.57697893 0.37747966 0.51459034 0.51081218 0.47681174 0.56433433
 0.47493628 0.5620089  0.57974374 0.39817201]


In [9]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(np.hstack((arr, arr[:, [0]])).shape)

(3, 4)


In [11]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr[:, [0]])
print(arr[:, [0]].shape)
print(np.hstack((arr, arr[:, [0]])).shape)

[[1]
 [4]
 [7]]
(3, 1)
(3, 4)


In [12]:
import numpy as np

arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])   # shape (3,3)

arr2 = np.array([[10,11],
                 [12,13],
                 [14,15]])   # shape (3,2)

result = np.hstack((arr1, arr2))
print(result)
print(result.shape)


[[ 1  2  3 10 11]
 [ 4  5  6 12 13]
 [ 7  8  9 14 15]]
(3, 5)


In [ ]:
a = np.array([1.2, 3.4 , 5.6])
a.astype(int)
b = max(a)+1
print(b)

11.2


In [19]:
5%2

1