#Agenda 
1. as type
2. indexing & slicing
3. np.arrange
4. fancy indexing
5. 2d matrix
6. aggregate function 
7. np.all
8. np.any
9. np.where
10. sort
11. matrix multiplication 


In [10]:
import numpy as np
a = np.array(['1.2', '3.4'])
type(a)
a.dtype

dtype('<U3')

In [16]:
a = np.array(["1" , "1.4" , "-2" , "2.5"])
a.dtype
a.astype(float )


array([ 1. ,  1.4, -2. ,  2.5])

In [ ]:
# this will leave the decimal part and convert to int (truncation)

arr = np.array([1.2, 3.4 , 5.6])
arr.astype(int)

array([1, 3, 5])

In [ ]:
# this will round the values to the nearest integer before converting to int

arr = np.array([1.2, 3.4 , 5.6])
np.round(arr).astype(int)

array([1, 3, 6])

#indexing

In [12]:
import numpy as np
a = np.arange(22,71 ,2)
a

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [16]:
a= np.arange(21,72 ,2)
a

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [17]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

1.0


In [18]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

21


In [24]:
arr = np.array([[0, 1, 2], 
                [3, 4, 5], 
                [6, 7, 8]])
reverse = arr[:, ::-1]

print(reverse)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


parrot


TypeError: 'numpy.int64' object is not callable

In [37]:
a = np.array([1.2, 3.4 , 5.6 ,10.2 , 7.8, 1.3 , 2.5 , 4.6 , 8.9])
print(a)
b = np.sort(a)
print(b)
c = np.argsort(a)
print("argsort:", c)
d = a[c]
print(d)
e = np.argmax(a)
print(e)

[ 1.2  3.4  5.6 10.2  7.8  1.3  2.5  4.6  8.9]
[ 1.2  1.3  2.5  3.4  4.6  5.6  7.8  8.9 10.2]
argsort: [0 5 6 1 7 2 4 8 3]
[ 1.2  1.3  2.5  3.4  4.6  5.6  7.8  8.9 10.2]
3


In [53]:
arr = np.array([[3, 7, 1],
                [9, 10, 12],
                [4, 6, 8]])
max_indices = np.argmax(arr,axis=1)
print(max_indices)

[1 2 2]
