In [ ]:
# =========================
# 1) Imports
# =========================

import numpy as np            # numerical arrays and math
import pandas as pd           # tabular data handling



In [ ]:
x = -7
lr =0.01
for i in range(20):
  x = x - lr*2*x
  print(x)

-6.86
-6.7228
-6.588344
-6.45657712
-6.327445577600001
-6.200896666048001
-6.076878732727041
-5.9553411580725
-5.83623433491105
-5.71950964821283
-5.605119455248573
-5.493017066143602
-5.383156724820729
-5.275493590324315
-5.169983718517829
-5.066584044147472
-4.965252363264523
-4.865947315999232
-4.768628369679248
-4.673255802285663


In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [ ]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [ ]:
def init_params(layer_sizes):

  np.random.seed(3)
  params = {}
  L = len(layer_sizes)

  for l in range(1, L):

    params['W' + str(l)] = np.ones((layer_sizes[l-1], layer_sizes[l]))*0.1
    params['b' + str(l)] = np.zeros((layer_sizes[l], 1))


  return params

In [ ]:
init_params([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward_step(activ_prev, weights, bias):

  Z = np.dot(weights.T, activ_prev) + bias

  return Z

In [ ]:
# Forward Prop
def forward_pass(input_data, params):

  A = input_data
  L = len(params) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    activ_prev = A
    Wl = params['W' + str(l)]
    bl = params['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward_step(activ_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,activ_prev

In [ ]:
input_data = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
target = df[['lpa']].values[0][0]

# Parameter initialization
params = init_params([2,2,1])

y_pred,hidden_activ = forward_pass(input_data, params)

In [ ]:
hidden_activ

array([[1.6],
       [1.6]])

In [ ]:
y_pred

array([[0.32]])

In [ ]:
y_pred = y_pred[0][0]

In [ ]:
params

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
input_data

array([[8],
       [8]])

In [ ]:
y_pred

np.float64(0.32000000000000006)

In [ ]:
params

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def update_params(params,target,y_pred,hidden_activ,input_data):
  params['W2'][0][0] = params['W2'][0][0] + (0.001 * 2 * (target - y_pred)*hidden_activ[0][0])
  params['W2'][1][0] = params['W2'][1][0] + (0.001 * 2 * (target - y_pred)*hidden_activ[1][0])
  params['b2'][0][0] = params['W2'][1][0] + (0.001 * 2 * (target - y_pred))

  params['W1'][0][0] = params['W1'][0][0] + (0.001 * 2 * (target - y_pred)*params['W2'][0][0]*input_data[0][0])
  params['W1'][0][1] = params['W1'][0][1] + (0.001 * 2 * (target - y_pred)*params['W2'][0][0]*input_data[1][0])
  params['b1'][0][0] = params['b1'][0][0] + (0.001 * 2 * (target - y_pred)*params['W2'][0][0])

  params['W1'][1][0] = params['W1'][1][0] + (0.001 * 2 * (target - y_pred)*params['W2'][1][0]*input_data[0][0])
  params['W1'][1][1] = params['W1'][1][1] + (0.001 * 2 * (target - y_pred)*params['W2'][1][0]*input_data[1][0])
  params['b1'][1][0] = params['b1'][1][0] + (0.001 * 2 * (target - y_pred)*params['W2'][1][0])

In [ ]:
input_data = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
target = df[['lpa']].values[0][0]

# Parameter initialization
params = init_params([2,2,1])

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [ ]:
input_data = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
target = df[['lpa']].values[1][0]

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [ ]:
input_data = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
target = df[['lpa']].values[2][0]

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [ ]:
input_data = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
target = df[['lpa']].values[3][0]

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [ ]:
# epochs implementation

params = init_params([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    input_data = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    target = df[['lpa']].values[j][0]

    # Parameter initialization


    y_pred,hidden_activ = forward_pass(input_data,params)
    y_pred = y_pred[0][0]

    update_params(params,target,y_pred,hidden_activ,input_data)

    Loss.append((target-y_pred)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

params

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}