In [1]:
import numpy as np
import pandas as pd

x = -7 
lr = 0.01
for i in range(20):
    x = x - lr * (2 * x)
    print(f"Iteration {i+1}: x = {x}")

Iteration 1: x = -6.86
Iteration 2: x = -6.7228
Iteration 3: x = -6.588344
Iteration 4: x = -6.45657712
Iteration 5: x = -6.327445577600001
Iteration 6: x = -6.200896666048001
Iteration 7: x = -6.076878732727041
Iteration 8: x = -5.9553411580725
Iteration 9: x = -5.83623433491105
Iteration 10: x = -5.71950964821283
Iteration 11: x = -5.605119455248573
Iteration 12: x = -5.493017066143602
Iteration 13: x = -5.383156724820729
Iteration 14: x = -5.275493590324315
Iteration 15: x = -5.169983718517829
Iteration 16: x = -5.066584044147472
Iteration 17: x = -4.965252363264523
Iteration 18: x = -4.865947315999232
Iteration 19: x = -4.768628369679248
Iteration 20: x = -4.673255802285663


In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
def init_params(layer_sizes):
    np.random.seed(3)
    params = {}
    L = len(layer_sizes)
    for l in range(1, L):
        params['W' + str(l)] = np.ones((layer_sizes[l], layer_sizes[l-1])) * 0.1
        params['b' + str(l)] = np.zeros((layer_sizes[l], 1))
    return params

In [6]:
init_params([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1, 0.1]]),
 'b2': array([[0.]])}

In [35]:
def linear_forward_step(A_prev, W, b):
    Z = np.dot(W, A_prev) + b
    return Z

In [14]:
def forward_pass(input_data, params):
    A = input_data
    L = len(params) // 2
    for l in range(1, L + 1):
        active_prev = A
        Wl = params['W' + str(l)]
        bl = params['b' + str(l)]
        A = linear_forward_step(active_prev, Wl, bl)
    return A , active_prev

In [16]:
input_data = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
target = df[['lpa']].values[0][0]
params = init_params([2, 2, 1])
def linear_forward_step(A_prev, W, b):
    return np.dot(W, A_prev) + b

y_pred, hidden_active = forward_pass(input_data, params)


In [18]:
hidden_active

array([[1.6],
       [1.6]])

In [19]:
y_pred

array([[0.32]])

In [20]:
y_pred = y_pred[0][0]

In [21]:
y_pred

np.float64(0.32000000000000006)

In [22]:
params

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1, 0.1]]),
 'b2': array([[0.]])}

In [23]:
input_data

array([[8],
       [8]])

In [25]:
y_pred

np.float64(0.32000000000000006)

In [37]:
def update_params(params,target,y_pred,hidden_activ,input_data):
  params['W2'][0][0] = params['W2'][0][0] + (0.001 * 2 * (target - y_pred)*hidden_activ[0][0])
  params['W2'][0][1] = params['W2'][0][1] + (0.001 * 2 * (target - y_pred)*hidden_activ[1][0])
  params['b2'][0][0] = params['b2'][0][0] + (0.001 * 2 * (target - y_pred))

  params['W1'][0][0] = params['W1'][0][0] + (0.001 * 2 * (target - y_pred)*params['W2'][0][0]*input_data[0][0])
  params['W1'][0][1] = params['W1'][0][1] + (0.001 * 2 * (target - y_pred)*params['W2'][0][0]*input_data[1][0])
  params['b1'][0][0] = params['b1'][0][0] + (0.001 * 2 * (target - y_pred)*params['W2'][0][0])

  params['W1'][1][0] = params['W1'][1][0] + (0.001 * 2 * (target - y_pred)*params['W2'][0][1]*input_data[0][0])
  params['W1'][1][1] = params['W1'][1][1] + (0.001 * 2 * (target - y_pred)*params['W2'][0][1]*input_data[1][0])
  params['b1'][1][0] = params['b1'][1][0] + (0.001 * 2 * (target - y_pred)*params['W2'][0][1])

In [39]:
input_data = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
target = df[['lpa']].values[0][0]

# Parameter initialization
params = init_params([2,2,1])

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776, 0.111776]]),
 'b2': array([[0.00736]])}

In [40]:
input_data = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
target = df[['lpa']].values[1][0]

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.11481311, 0.11716504],
        [0.11481311, 0.11716504]]),
 'b1': array([[0.00199863],
        [0.00199863]]),
 'W2': array([[0.12751067, 0.12751067]]),
 'b2': array([[0.01658246]])}

In [41]:
input_data = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
target = df[['lpa']].values[2][0]

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.12459806, 0.13347329],
        [0.12459806, 0.13347329]]),
 'b1': array([[0.00362946],
        [0.00362946]]),
 'W2': array([[0.14802989, 0.14802989]]),
 'b2': array([[0.02759933]])}

In [42]:
input_data = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
target = df[['lpa']].values[3][0]

y_pred,hidden_activ = forward_pass(input_data,params)
y_pred = y_pred[0][0]

update_params(params,target,y_pred,hidden_activ,input_data)

params

{'W1': array([[0.13571869, 0.1601628 ],
        [0.13571869, 0.1601628 ]]),
 'b1': array([[0.00585359],
        [0.00585359]]),
 'W2': array([[0.17616302, 0.17616302]]),
 'b2': array([[0.04022471]])}

In [45]:
# epochs implementation

params = init_params([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    input_data = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    target = df[['lpa']].values[j][0]

    # Parameter initialization


    y_pred,hidden_activ = forward_pass(input_data,params)
    y_pred = y_pred[0][0]

    update_params(params,target,y_pred,hidden_activ,input_data)

    Loss.append((target-y_pred)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

params

Epoch -  1 Loss -  26.249691774703265
Epoch -  2 Loss -  19.19634375189233
Epoch -  3 Loss -  9.702531836210806
Epoch -  4 Loss -  3.0274162602080916
Epoch -  5 Loss -  1.0597082587765176


{'W1': array([[0.27790431, 0.40579137],
        [0.27790431, 0.40579137]]),
 'b1': array([[0.0295198],
        [0.0295198]]),
 'W2': array([[0.46411039, 0.46411039]]),
 'b2': array([[0.11664796]])}