In [ ]:
# Install TensorFlow
# pip install tensorflow

# Import required libraries
import tensorflow as tf
import numpy as np

# Check TensorFlow version
print(f"TensorFlow Version: {tf.__version__}")
# Output: TensorFlow Version: 2.x.x

TensorFlow Version: 2.19.0


In [ ]:
tf.config.list_physical_devices('GPU')

[]

In [ ]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tensor_from_list = tf.constant([1, 2, 3, 4, 5])
tensor_from_list

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
numpy_array = np.array([[1, 2], [3, 4], [5, 6]])
tensor_from_numpy = tf.constant(numpy_array)

In [ ]:
tensor_from_numpy

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
zeros_tensor = tf.zeros([3, 3])  # 3x3 matrix of zeros
zeros_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
ones_tensor = tf.ones([2, 4])    # 2x4 matrix of ones
ones_tensor

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
identity_matrix = tf.eye(3)      # 3x3 identity matrix
identity_matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
np.random.rand(2,3)

array([[0.68633716, 0.58549371, 0.02320634],
       [0.81964672, 0.02762782, 0.26706847]])

In [ ]:
random_tensor = tf.random.normal([2, 3])  # Random normal distribution
random_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.0986273 , -0.5184813 ,  0.04940577],
       [ 0.02853042,  0.6373974 ,  0.53362113]], dtype=float32)>

In [ ]:
a = np.array([1,2,3])
b =  np.array([[1,2,3]])
c =  np.array([[[1,2,3]]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
b

array([[1, 2, 3]])

In [ ]:
b.ndim

2

In [ ]:
c

array([[[1, 2, 3]]])

In [ ]:
c.ndim

3

In [ ]:
# Understanding tensor properties is crucial for debugging

sample_tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

# Shape: Dimensions of the tensor
print(f"Shape: {sample_tensor.shape}")
# Output: Shape: (2, 3) - 2 rows, 3 columns

# Rank: Number of dimensions
print(f"Rank: {tf.rank(sample_tensor)}")
# Output: Rank: tf.Tensor(2, shape=(), dtype=int32)

# Size: Total number of elements
print(f"Size: {tf.size(sample_tensor)}")
# Output: Size: tf.Tensor(6, shape=(), dtype=int32)

# Data type
print(f"Data type: {sample_tensor.dtype}")
# Output: Data type: <dtype: 'float32'>

Shape: (2, 3)
Rank: 2
Size: 6
Data type: <dtype: 'float32'>


In [ ]:
sample_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
a = [[[1, 2, 3], [4, 5, 6],[1, 2, 3],[1, 2, 3]]]
b = tf.constant(a)

In [ ]:
b

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [ ]:
b.shape

TensorShape([1, 4, 3])

In [ ]:
b.reshape(6,2,1)

AttributeError: EagerTensor object has no attribute 'reshape'. 
        If you are looking for numpy-related methods, please run the following:
        tf.experimental.numpy.experimental_enable_numpy_behavior()
      

In [ ]:
b

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [ ]:
z = tf.reshape(b,(6,2,1))

In [ ]:
# Element-wise operations
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Addition
add_result = tf.add(a, b)  # or simply a + b
print(f"Addition:\n{add_result}")
# Output: [[6. 8.] [10. 12.]]

# Multiplication (element-wise)
multiply_result = tf.multiply(a, b)  # or a * b
print(f"Element-wise multiplication:\n{multiply_result}")
# Output: [[5. 12.] [21. 32.]]

# Matrix multiplication (dot product)
matmul_result = tf.matmul(a, b)  # or a @ b
print(f"Matrix multiplication:\n{matmul_result}")
# Output: [[19. 22.] [43. 50.]]
# Explanation: [1*5+2*7, 1*6+2*8] = [19, 22] for first row

# Reduction operations
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

Addition:
[[ 6.  8.]
 [10. 12.]]
Element-wise multiplication:
[[ 5. 12.]
 [21. 32.]]
Matrix multiplication:
[[19. 22.]
 [43. 50.]]


#2. Reduction operations


In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
tensor


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
# Mean across all elements
mean_all = tf.reduce_mean(tensor)
print(f"Mean of all elements: {mean_all}")
# Output: Mean of all elements: 3.5

# Sum along axis (axis=0: columns, axis=1: rows)
sum_columns = tf.reduce_sum(tensor, axis=0)
sum_rows = tf.reduce_sum(tensor, axis=1)
print(f"Sum along columns: {sum_columns}")  # Output: [5. 7. 9.]
print(f"Sum along rows: {sum_rows}")        # Output: [6. 15.]

Mean of all elements: 3.5
Sum along columns: [5. 7. 9.]
Sum along rows: [ 6. 15.]


In [ ]:
z

<tf.Tensor: shape=(6, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[1],
        [2]],

       [[3],
        [1]],

       [[2],
        [3]]], dtype=int32)>

In [ ]:
tf.rank(z)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tf.reshape(z,-1) # Flatten

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [ ]:
#transposed = tf.transpose(original)


In [ ]:
F = tf.constant([0.2, 0.8, 0.5])
print(F.numpy())  # [0.2 0.8 0.5]


[0.2 0.8 0.5]


In [ ]:
print(tf.reduce_max(F))  # 0.8 (biggest number)
print(tf.reduce_min(F))  # 0.2 (smallest number)

tf.Tensor(0.8, shape=(), dtype=float32)
tf.Tensor(0.2, shape=(), dtype=float32)


In [ ]:
print(tf.reduce_max(F).numpy())  # 0.8 (biggest number)
print(tf.reduce_min(F).numpy())  # 0.2 (smallest number)

0.8
0.2


In [ ]:
print(tf.argmax(F).numpy())  # 1 → position of biggest (0.8)
print(tf.argmin(F).numpy())  # 0 → position of smallest (0.2)

1
0


In [ ]:
 tf.expand_dims(original, axis=0)

In [ ]:
@tf.function
def fun(x1,x2):
  return x1+x2

In [ ]:
@tf.function

In [ ]:
# Complete, minimal NN with manual forward + backward (TensorFlow 2.x)
import tensorflow as tf
import numpy as np
import time

# Reproducibility
tf.random.set_seed(42)
np.random.seed(42)

# -----------------------
# 1) Create synthetic dataset (simple linear function + noise)
# -----------------------
N = 500            # number of samples
X = np.random.uniform(-1, 1, size=(N, 1)).astype(np.float32)   # shape (N, 1)
true_w = 3.0
true_b = 2.0
noise = np.random.normal(0.0, 0.1, size=(N, 1)).astype(np.float32)
Y = (true_w * X + true_b + noise).astype(np.float32)          # shape (N, 1)

# Convert to tf tensors
X_tf = tf.constant(X)   # input
Y_tf = tf.constant(Y)   # targets

# -----------------------
# 2) Define network architecture and initialize weights (as tf.Variable)
#    Simple 1-hidden-layer network: input(1) -> hidden(8) -> output(1)
# -----------------------
input_dim = 1
hidden_units = 8
output_dim = 1

# Initialize weights and biases
W1 = tf.Variable(tf.random.normal([input_dim, hidden_units], stddev=0.5), name="W1")
b1 = tf.Variable(tf.zeros([hidden_units]), name="b1")

W2 = tf.Variable(tf.random.normal([hidden_units, output_dim], stddev=0.5), name="W2")
b2 = tf.Variable(tf.zeros([output_dim]), name="b2")

# -----------------------
# 3) Define forward pass (pure tensor ops)
# -----------------------
def forward_pass(x):
    """Compute network output for input x."""
    # Linear -> ReLU -> Linear (no activation on output for regression)
    z1 = tf.matmul(x, W1) + b1           # shape (batch, hidden_units)
    a1 = tf.nn.relu(z1)                  # activation
    out = tf.matmul(a1, W2) + b2         # shape (batch, output_dim)
    return out

# -----------------------
# 4) Define loss function (Mean Squared Error)
# -----------------------
def mse_loss(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

# -----------------------
# 5) Training hyperparameters
# -----------------------
learning_rate = 0.1
epochs = 200
batch_size = 32
steps_per_epoch = int(np.ceil(N / batch_size))

# -----------------------
# 6) Manual training loop with GradientTape (explicit backward pass)
# -----------------------
start_time = time.time()
for epoch in range(1, epochs + 1):
    # Shuffle the data indices
    idx = np.random.permutation(N)
    X_shuffled = X_tf.numpy()[idx]
    Y_shuffled = Y_tf.numpy()[idx]

    epoch_loss = 0.0

    for step in range(steps_per_epoch):
        start = step * batch_size
        end = min(start + batch_size, N)
        x_batch = tf.constant(X_shuffled[start:end])
        y_batch = tf.constant(Y_shuffled[start:end])

        # Record operations for automatic differentiation
        with tf.GradientTape() as tape:
            y_pred = forward_pass(x_batch)          # forward
            loss = mse_loss(y_pred, y_batch)        # compute loss

        # Backward: compute gradients of loss w.r.t. all trainable variables
        grads = tape.gradient(loss, [W1, b1, W2, b2])

        # Manual SGD parameter update: param = param - lr * grad
        W1.assign_sub(learning_rate * grads[0])
        b1.assign_sub(learning_rate * grads[1])
        W2.assign_sub(learning_rate * grads[2])
        b2.assign_sub(learning_rate * grads[3])

        epoch_loss += loss.numpy() * (end - start)

    # average loss over dataset
    epoch_loss /= N

    # print some progress
    if epoch % 20 == 0 or epoch == 1:
        print(f"Epoch {epoch:3d}/{epochs} - Loss: {epoch_loss:.6f}")

end_time = time.time()
print(f"Training finished in {end_time - start_time:.3f} seconds")

# -----------------------
# 7) Evaluate learned parameters and final loss on full dataset
# -----------------------
y_pred_final = forward_pass(X_tf)
final_loss = mse_loss(y_pred_final, Y_tf).numpy()
print("\nFinal MSE on training set:", final_loss)

# Print learned linear approximation for sanity (since target is linear)
# Note: The small hidden net should be able to represent a linear mapping approx.
# We can run a simple least-square on predictions to see approximate slope/intercept.
coef = np.polyfit(X.flatten(), y_pred_final.numpy().flatten(), 1)
print(f"Learned linear fit (approx): y = {coef[0]:.3f}x + {coef[1]:.3f}")
print(f"True function was y = {true_w}x + {true_b}")

# -----------------------
# 8) Inference example: predict on a new point
# -----------------------
x_test = tf.constant([[0.5]], dtype=tf.float32)
y_test_pred = forward_pass(x_test).numpy().squeeze()
y_test_true = true_w * 0.5 + true_b
print(f"\nFor x = 0.5, predicted y = {y_test_pred:.3f}, true y = {y_test_true:.3f}")


Epoch   1/200 - Loss: 1.908134
Epoch  20/200 - Loss: 0.011679
Epoch  40/200 - Loss: 0.010776
Epoch  60/200 - Loss: 0.011041
Epoch  80/200 - Loss: 0.010321
Epoch 100/200 - Loss: 0.010541
Epoch 120/200 - Loss: 0.010535
Epoch 140/200 - Loss: 0.010752
Epoch 160/200 - Loss: 0.010938
Epoch 180/200 - Loss: 0.010708
Epoch 200/200 - Loss: 0.010354
Training finished in 20.195 seconds

Final MSE on training set: 0.010461627
Learned linear fit (approx): y = 3.020x + 2.023
True function was y = 3.0x + 2.0

For x = 0.5, predicted y = 3.543, true y = 3.500
